### ISSUE TITLE
modal de email instituicional

### ISSUE THREAD

**Issue by BryanDavidAlves** [BryanDavidAlves/TrampoTec#317]
fazer o modal na tela de login do aluno, para notificar o aluno que é necessário ser um email instituicional da etec

**Comment by Johnydbr** [comment]
eae

**Comment by BryanDavidAlves** [comment]
@Johnydbr vc tem quanto anos?

**Comment by Johnydbr** [comment]
@BryanDavidAlves  18 anos

**Comment by BryanDavidAlves** [comment]
aaaa
